var importantItems = [
  'Bow',
  'Progressive Hookshot',
  'Hammer',
  'Slingshot',
  'Boomerang',
  'Bomb Bag',
  'Lens of Truth',
  'Dins Fire',
  'Farores Wind',
  'Nayrus Love',
  'Fire Arrows',
  'Ice Arrows',
  'Light Arrows',
  'Fairy Ocarina',
  'Ocarina of Time',
  'Ocarina',
  'Bottle',
  'Bottle with Letter',
  'Bottle with Milk',
  'Bottle with Red Potion',
  'Bottle with Green Potion',
  'Bottle with Blue Potion',
  'Bottle with Fairy',
  'Bottle with Fish',
  'Bottle with Blue Fire',
  'Bottle with Bugs',
  'Bottle with Poe',
  'Weird Egg',
  'Pocket Egg',
  'Pocket Cucco',
  'Cojiro',
  'Odd Mushroom',
  'Odd Potion',
  'Poachers Saw',
  'Broken Sword',
  'Prescription',
  'Eyeball Frog',
  'Eyedrops',
  'Claim Check',
  'Kokiri Sword',
  'Master Sword',
  'Biggoron Sword',
  'Mirror Shield',
  'Goron Tunic',
  'Zora Tunic',
  'Iron Boots',
  'Hover Boots',
  'Progressive Strength Upgrade',
  'Progressive Scale',
  'Progressive Wallet',
  'Magic Meter',
  'Stone of Agony',
  'Bombchus (5)',
  'Bombchus (10)',
  'Bombchus (20)',
  'Bombchus',
  'Magic Bean',
  'Boss Key',
  'Small Key',
  'Boss Key (Forest Temple)',
  'Boss Key (Fire Temple)',
  'Boss Key (Water Temple)',
  'Boss Key (Spirit Temple)',
  'Boss Key (Shadow Temple)',
  'Boss Key (Ganons Castle)',
  'Small Key (Forest Temple)',
  'Small Key (Fire Temple)',
  'Small Key (Water Temple)',
  'Small Key (Spirit Temple)',
  'Small Key (Shadow Temple)',
  'Small Key (Bottom of the Well)',
  'Small Key (Gerudo Training Grounds)',
  'Small Key (Gerudo Fortress)',
  'Small Key (Ganons Castle)',
  'Zeldas Letter',
  'Zeldas Lullaby',
  'Eponas Song',
  'Suns Song',
  'Sarias Song',
  'Song of Time',
  'Song of Storms',
  'Minuet of Forest',
  'Prelude of Light',
  'Bolero of Fire',
  'Serenade of Water',
  'Nocturne of Shadow',
  'Requiem of Spirit',
  'Gold Skulltulla Token',
  'Epona',
  'Gerudo Membership Card',
  'Forest Trial Clear',
  'Fire Trial Clear',
  'Water Trial Clear',
  'Shadow Trial Clear',
  'Spirit Trial Clear',
  'Light Trial Clear',
  'Triforce',
];

var inSpoilerExceptions = ['Check Pedestal (Stones)', 'Check Pedestal (Medallions)', 'Light Arrows Hint', 'Ganon'];

hashImages = {
    'Deku Stick': 'stick.png',
    'Deku Nut': 'nut.png',
    'Bow': 'bow.png',
    'Slingshot': 'slingshot.png',
    'Fairy Ocarina': 'fairyocarina.png',
    'Bombchu': 'bombchu.png',
    'Longshot': 'longshot.png',
    'Boomerang': 'boomerang.png',
    'Lens of Truth': 'lens.png',
    'Beans': 'bean.png',
    'Hammer': 'hammer.png',
    'Bottled Fish': 'fish.png',
    'Bottled Milk': 'milk.png',
    'Mask of Truth': 'truth.png',
    'SOLD OUT': 'soldout.png',
    'Cucco': 'cucco.png',
    'Mushroom': 'mushroom.png',
    'Saw': 'saw.png',
    'Frog': 'frog.png',
    'Master Sword': 'sword2.png',
    'Mirror Shield': 'shield3.png',
    'Kokiri Tunic': 'greentunic.png',
    'Hover Boots': 'hoverboots.png',
    'Silver Gauntlets': 'lift2.png',
    'Gold Scale': 'scale2.png',
    'Stone of Agony': 'agony.png',
    'Skull Token': 'skulltula.png',
    'Heart Container': 'heartcontainer.png',
    'Boss Key': 'boss_key.png',
    'Compass': 'compass.png',
    'Map': 'map.png',
    'Big Magic': 'magic2.png',
  };
  
var hintItemsMeanings = {
  "mystic training": "Magic Meter",
  "pixie dust": "Magic Meter",
  "a green rectangle": "Magic Meter",
  "a Magic Meter": "Magic Meter",
  "a white outline": "Double Defense",
  "damage decrease": "Double Defense",
  "strengthened love": "Double Defense",
  "Double Defense": "Double Defense",
  "a seed shooter": "Slingshot",
  "a rubberband": "Slingshot",
  "a child's catapult": "Slingshot",
  "a Slingshot": "Slingshot",
  "a banana": "Boomerang",
  "a stun stick": "Boomerang",
  "the Boomerang": "Boomerang",
  "an archery enabler": "Bow",
  "a danger dart launcher": "Bow",
  "a Bow": "Bow",
  "an explosive container": "Bomb Bag",
  "a blast bag": "Bomb Bag",
  "a Bomb Bag": "Bomb Bag",
  "Dampe's keepsake": "Progressive Hookshot",
  "the Grapple Beam": "Progressive Hookshot",
  "the BOING! chain": "Progressive Hookshot",
  "a Hookshot": "Progressive Hookshot",
  "power gloves": "Progressive Strength Upgrade",
  "metal mittens": "Progressive Strength Upgrade",
  "the heavy lifty": "Progressive Strength Upgrade",
  "a Strength Upgrade": "Progressive Strength Upgrade",
  "a deeper dive": "Progressive Scale",
  "a piece of Zora": "Progressive Scale",
  "a Zora Scale": "Progressive Scale",
  "the dragon smasher": "Hammer",
  "the metal mallet": "Hammer",
  "the heavy hitter": "Hammer",
  "the Megaton Hammer": "Hammer",
  "sink shoes": "Iron Boots",
  "clank cleats": "Iron Boots",
  "the Iron Boots": "Iron Boots",
  "butter boots": "Hover Boots",
  "sacred slippers": "Hover Boots",
  "spacewalkers": "Hover Boots",
  "the Hover Boots": "Hover Boots",
  "a butter knife": "Kokiri Sword",
  "a starter slasher": "Kokiri Sword",
  "a switchblade": "Kokiri Sword",
  "the Kokiri Sword": "Kokiri Sword",
  "the biggest blade": "Biggoron Sword",
  "a colossal cleaver": "Biggoron Sword",
  "the Biggoron Sword": "Biggoron Sword",
  "evil's bane": "Master Sword",
  "the Master Sword": "Master Sword",
  "a wooden ward": "Deku Shield",
  "a burnable barrier": "Deku Shield",
  "a Deku Shield": "Deku Shield",
  "a steel safeguard": "Hylian Shield",
  "Like Like's metal meal": "Hylian Shield",
  "a Hylian Shield": "Hylian Shield",
  "the reflective rampart": "Mirror Shield",
  "Medusa's weakness": "Mirror Shield",
  "a silvered surface": "Mirror Shield",
  "the Mirror Shield": "Mirror Shield",
  "teleportation": "Farores Wind",
  "a relocation rune": "Farores Wind",
  "a green ball": "Farores Wind",
  "a green gust": "Farores Wind",
  "Farore's Wind": "Farores Wind",
  "a safe space": "Nayrus Love",
  "an impregnable aura": "Nayrus Love",
  "a blue barrier": "Nayrus Love",
  "a blue crystal": "Nayrus Love",
  "Nayru's Love": "Nayrus Love",
  "an inferno": "Dins Fire",
  "a heat wave": "Dins Fire",
  "a red ball": "Dins Fire",
  "Din's Fire": "Dins Fire",
  "the furnace firearm": "Fire Arrows",
  "the burning bolts": "Fire Arrows",
  "a magma missile": "Fire Arrows",
  "the Fire Arrows": "Fire Arrows",
  "the refrigerator rocket": "Ice Arrows",
  "the frostbite bolts": "Ice Arrows",
  "an iceberg maker": "Ice Arrows",
  "the Ice Arrows": "Ice Arrows",
  "the shining shot": "Light Arrows",
  "the luminous launcher": "Light Arrows",
  "Ganondorf's bane": "Light Arrows",
  "the lighting bolts": "Light Arrows",
  "the Light Arrows": "Light Arrows",
  "a lie detector": "Lens of Truth",
  "a ghost tracker": "Lens of Truth",
  "true sight": "Lens of Truth",
  "a detective's tool": "Lens of Truth",
  "the Lens of Truth": "Lens of Truth",
  "a flute": "Ocarina",
  "a music maker": "Ocarina",
  "an Ocarina": "Ocarina",
  "ruby robes": "Goron Tunic",
  "fireproof fabric": "Goron Tunic",
  "cooking clothes": "Goron Tunic",
  "a Goron Tunic": "Goron Tunic",
  "a sapphire suit": "Zora Tunic",
  "scuba gear": "Zora Tunic",
  "a swimsuit": "Zora Tunic",
  "a Zora Tunic": "Zora Tunic",
  "a horse": "Epona",
  "a four legged friend": "Epona",
  "Epona": "Epona",
  "a song of royal slumber": "Zeldas Lullaby",
  "a triforce tune": "Zeldas Lullaby",
  "Zelda's Lullaby": "Zeldas Lullaby",
  "an equestrian etude": "Eponas Song",
  "Malon's melody": "Eponas Song",
  "a ranch song": "Eponas Song",
  "Epona's Song": "Eponas Song",
  "a song of dancing Gorons": "Sarias Song",
  "Saria's phone number": "Sarias Song",
  "Saria's Song": "Sarias Song",
  "Sunny Day": "Suns Song",
  "the ReDead's bane": "Suns Song",
  "the Gibdo's bane": "Suns Song",
  "the Sun's Song": "Suns Song",
  "a song 7 years long": "Song of Time",
  "the tune of ages": "Song of Time",
  "the Song of Time": "Song of Time",
  "Rain Dance": "Song of Storms",
  "a thunderstorm tune": "Song of Storms",
  "windmill acceleration": "Song of Storms",
  "the Song of Storms": "Song of Storms",
  "the song of tall trees": "Minuet of Forest",
  "an arboreal anthem": "Minuet of Forest",
  "a green spark trail": "Minuet of Forest",
  "the Minuet of Forest": "Minuet of Forest",
  "a song of lethal lava": "Bolero of Fire",
  "a red spark trail": "Bolero of Fire",
  "a volcanic verse": "Bolero of Fire",
  "the Bolero of Fire": "Bolero of Fire",
  "a song of a damp ditch": "Serenade of Water",
  "a blue spark trail": "Serenade of Water",
  "the lake's lyric": "Serenade of Water",
  "the Serenade of Water": "Serenade of Water",
  "a song of sandy statues": "Requiem of Spirit",
  "an orange spark trail": "Requiem of Spirit",
  "the desert ditty": "Requiem of Spirit",
  "the Requiem of Spirit": "Requiem of Spirit",
  "a song of spooky spirits": "Nocturne of Shadow",
  "a graveyard boogie": "Nocturne of Shadow",
  "a haunted hymn": "Nocturne of Shadow",
  "a purple spark trail": "Nocturne of Shadow",
  "the Nocturne of Shadow": "Nocturne of Shadow",
  "a luminous prologue melody": "Prelude of Light",
  "a yellow spark trail": "Prelude of Light",
  "the temple traveler": "Prelude of Light",
  "the Prelude of Light": "Prelude of Light",
  "a glass container": "Bottle",
  "an empty jar": "Bottle",
  "encased air": "Bottle",
  "a Bottle": "Bottle",
  "a call for help": "Bottle with Letter",
  "the note that Mweeps": "Bottle with Letter",
  "an SOS call": "Bottle with Letter",
  "a fishy stationery": "Bottle with Letter",
  "Ruto's Letter": "Bottle with Letter",
  "cow juice": "Bottle with Milk",
  "a white liquid": "Bottle with Milk",
  "a baby's breakfast": "Bottle with Milk",
  "a Milk Bottle": "Bottle with Milk",
  "a vitality vial": "Bottle with Red Potion",
  "a red liquid": "Bottle with Red Potion",
  "a Red Potion Bottle": "Bottle with Red Potion",
  "a magic mixture": "Bottle with Green Potion",
  "a green liquid": "Bottle with Green Potion",
  "a Green Potion Bottle": "Bottle with Green Potion",
  "an ailment antidote": "Bottle with Blue Potion",
  "a blue liquid": "Bottle with Blue Potion",
  "a Blue Potion Bottle": "Bottle with Blue Potion",
  "an imprisoned fairy": "Bottle with Fairy",
  "an extra life": "Bottle with Fairy",
  "Navi's cousin": "Bottle with Fairy",
  "a Fairy Bottle": "Bottle with Fairy",
  "an aquarium": "Bottle with Fish",
  "a deity's snack": "Bottle with Fish",
  "a Fish Bottle": "Bottle with Fish",
  "a conflagration canteen": "Bottle with Blue Fire",
  "an icemelt jar": "Bottle with Blue Fire",
  "a Blue Fire Bottle": "Bottle with Blue Fire",
  "an insectarium": "Bottle with Bugs",
  "Skulltula finders": "Bottle with Bugs",
  "a Bug Bottle": "Bottle with Bugs",
  "a spooky ghost": "Bottle with Poe",
  "a face in the jar": "Bottle with Poe",
  "a Poe Bottle": "Bottle with Poe",
  "the spookiest ghost": "Bottle with Big Poe",
  "a sidequest spirit": "Bottle with Big Poe",
  "a Big Poe Bottle": "Bottle with Big Poe",
  "the shake stone": "Stone of Agony",
  "the Rumble Pak (TM)": "Stone of Agony",
  "the Stone of Agony": "Stone of Agony",
  "a girl club membership": "Gerudo Membership Card",
  "a desert tribe's pass": "Gerudo Membership Card",
  "the Gerudo Card": "Gerudo Membership Card",
  "a mo' money holder": "Progressive Wallet",
  "a gem purse": "Progressive Wallet",
  "a portable bank": "Progressive Wallet",
  "a Wallet": "Progressive Wallet",
  "a lumber rack": "Deku Stick Capacity",
  "more flammable twigs": "Deku Stick Capacity",
  "Deku Stick Capacity": "Deku Stick Capacity",
  "more nuts": "Deku Nut Capacity",
  "flashbang storage": "Deku Nut Capacity",
  "Deku Nut Capacity": "Deku Nut Capacity",
  "a lot of love": "Heart Container",
  "a Valentine's gift": "Heart Container",
  "a boss's organ": "Heart Container",
  "a Heart Container": "Heart Container",
  "a little love": "Piece of Heart",
  "a broken heart": "Piece of Heart",
  "a Piece of Heart": "Piece of Heart",
  "a victory valentine": "Piece of Heart (Treasure Chest Game)",
  "a free heal": "Recovery Heart",
  "a hearty meal": "Recovery Heart",
  "a Band-Aid": "Recovery Heart",
  "a Recovery Heart": "Recovery Heart",
  "the dollar of defeat": "Rupee (Treasure Chest Game)",
  "a breakable branch": "Deku Stick (1)",
  "a Deku Stick": "Deku Stick (1)",
  "a unique coin": "Rupee (1)",
  "a penny": "Rupee (1)",
  "a green gem": "Rupee (1)",
  "a Green Rupee": "Rupee (1)",
  "a common coin": "Rupees (5)",
  "a blue gem": "Rupees (5)",
  "a Blue Rupee": "Rupees (5)",
  "couch cash": "Rupees (20)",
  "a red gem": "Rupees (20)",
  "a Red Rupee": "Rupees (20)",
  "big bucks": "Rupees (50)",
  "a purple gem": "Rupees (50)",
  "wealth": "Rupees (50)",
  "a Purple Rupee": "Rupees (50)",
  "a juicy jackpot": "Rupees (200)",
  "a yellow gem": "Rupees (200)",
  "a giant gem": "Rupees (200)",
  "great wealth": "Rupees (200)",
  "a Huge Rupee": "Rupees (200)",
  "a chicken dilemma": "Weird Egg",
  "the Weird Egg": "Weird Egg",
  "an autograph": "Zeldas Letter",
  "royal stationery": "Zeldas Letter",
  "royal snail mail": "Zeldas Letter",
  "Zelda's Letter": "Zeldas Letter",
  "a Cucco container": "Pocket Egg",
  "a Cucco, eventually": "Pocket Egg",
  "a fowl youth": "Pocket Egg",
  "the Pocket Egg": "Pocket Egg",
  "a little clucker": "Pocket Cucco",
  "the Pocket Cucco": "Pocket Cucco",
  "a cerulean capon": "Cojiro",
  "Cojiro": "Cojiro",
  "a powder ingredient": "Odd Mushroom",
  "an Odd Mushroom": "Odd Mushroom",
  "Granny's goodies": "Odd Potion",
  "an Odd Potion": "Odd Potion",
  "a tree killer": "Poachers Saw",
  "the Poacher's Saw": "Poachers Saw",
  "a shattered slicer": "Broken Sword",
  "the Broken Sword": "Broken Sword",
  "a pill pamphlet": "Prescription",
  "a doctor's note": "Prescription",
  "the Prescription": "Prescription",
  "a perceiving polliwog": "Eyeball Frog",
  "the Eyeball Frog": "Eyeball Frog",
  "a vision vial": "Eyedrops",
  "the Eyedrops": "Eyedrops",
  "a three day wait": "Claim Check",
  "the Claim Check": "Claim Check",
  "a dungeon atlas": "Map",
  "blueprints": "Map",
  "a Map": "Map",
  "a treasure tracker": "Compass",
  "a magnetic needle": "Compass",
  "a Compass": "Compass",
  "a master of unlocking": "BossKey",
  "a dungeon's master pass": "BossKey",
  "a Boss Key": "BossKey",
  "a tool for unlocking": "SmallKey",
  "a dungeon pass": "SmallKey",
  "a lock remover": "SmallKey",
  "a lockpick": "SmallKey",
  "a Small Key": "SmallKey",
  "a get out of jail free card": "FortressSmallKey",
  "a Jail Key": "FortressSmallKey",
  "something mysterious": "KeyError",
  "an unknown treasure": "KeyError",
  "An Error (Please Report This)": "KeyError",
  "a few danger darts": "Arrows (5)",
  "a few sharp shafts": "Arrows (5)",
  "Arrows (5 pieces)": "Arrows (5)",
  "some danger darts": "Arrows (10)",
  "some sharp shafts": "Arrows (10)",
  "Arrows (10 pieces)": "Arrows (10)",
  "plenty of danger darts": "Arrows (30)",
  "plenty of sharp shafts": "Arrows (30)",
  "Arrows (30 pieces)": "Arrows (30)",
  "a few explosives": "Bombs (5)",
  "a few blast balls": "Bombs (5)",
  "Bombs (5 pieces)": "Bombs (5)",
  "some explosives": "Bombs (10)",
  "some blast balls": "Bombs (10)",
  "Bombs (10 pieces)": "Bombs (10)",
  "lots-o-explosives": "Bombs (20)",
  "plenty of blast balls": "Bombs (20)",
  "Bombs (20 pieces)": "Bombs (20)",
  "a gift from Ganon": "Ice Trap",
  "a chilling discovery": "Ice Trap",
  "frosty fun": "Ice Trap",
  "an Ice Trap": "Ice Trap",
  "wizardly legumes": "Magic Bean",
  "a Magic Bean": "Magic Bean",
  "mice bombs": "Bombchus",
  "proximity mice": "Bombchus",
  "wall crawlers": "Bombchus",
  "trail blazers": "Bombchus",
  "Bombchus": "Bombchus",
  "a few mice bombs": "Bombchus (5)",
  "a few proximity mice": "Bombchus (5)",
  "a few wall crawlers": "Bombchus (5)",
  "a few trail blazers": "Bombchus (5)",
  "Bombchus (5 pieces)": "Bombchus (5)",
  "some mice bombs": "Bombchus (10)",
  "some proximity mice": "Bombchus (10)",
  "some wall crawlers": "Bombchus (10)",
  "some trail blazers": "Bombchus (10)",
  "Bombchus (10 pieces)": "Bombchus (10)",
  "plenty of mice bombs": "Bombchus (20)",
  "plenty of proximity mice": "Bombchus (20)",
  "plenty of wall crawlers": "Bombchus (20)",
  "plenty of trail blazers": "Bombchus (20)",
  "Bombchus (20 pieces)": "Bombchus (20)",
  "some nuts": "Deku Nuts (5)",
  "some flashbangs": "Deku Nuts (5)",
  "some scrub spit": "Deku Nuts (5)",
  "Deku Nuts (5 pieces)": "Deku Nuts (5)",
  "lots-o-nuts": "Deku Nuts (10)",
  "plenty of flashbangs": "Deku Nuts (10)",
  "plenty of scrub spit": "Deku Nuts (10)",
  "Deku Nuts (10 pieces)": "Deku Nuts (10)",
  "catapult ammo": "Deku Seeds (30)",
  "lots-o-seeds": "Deku Seeds (30)",
  "Deku Seeds (30 pieces)": "Deku Seeds (30)",
  "proof of destruction": "Gold Skulltula Token",
  "an arachnid chip": "Gold Skulltula Token",
  "spider remains": "Gold Skulltula Token",
  "one percent of a curse": "Gold Skulltula Token",
  "a Gold Skulltula Token": "Gold Skulltula Token",
  "is a foolish choice": "Foolish Choice",
  "way of the hero": "Way of the Hero",

};

var hintLocationsMeanings = {
  "the Skull Kid grants": "Skull Kid",
  "collecting cuccos rewards": "Anjus Chickens",
  "Big Poes leads to": "10 Big Poes",
  "ghost hunters will be rewarded with": "10 Big Poes",
  "the Skull Mask yields": "Deku Theater Skull Mask",
  "the Mask of Truth yields": "Deku Theater Mask of Truth",
  "slaying 20 Gold Skulltulas reveals": "20 Gold Skulltula Reward",
  "slaying 30 Gold Skulltulas reveals": "30 Gold Skulltula Reward",
  "slaying 40 Gold Skulltulas reveals": "40 Gold Skulltula Reward",
  "slaying 50 Gold Skulltulas reveals": "50 Gold Skulltula Reward",
  "the treasure thrown by Princess Zelda is": "Ocarina of Time",
  "the Ocarina of Time teaches": "Song from Ocarina of Time",
  "Biggoron crafts": "Biggoron",
  "an amphibian feast yields": "Frog Ocarina Game",
  "the croaking choir's magnum opus awards": "Frog Ocarina Game",
  "the froggy finale yields": "Frog Ocarina Game",
  "the final reward from the Frogs of Zora's River is": "Frog Ocarina Game",
  "fishing in youth bestows": "Child Fishing",
  "fishing in maturity bestows": "Adult Fishing",
  "gambling grants": "Treasure Chest Game",
  "there is a 1/32 chance to win": "Treasure Chest Game",
  "the treasure chest game grants": "Treasure Chest Game",
  "Darunia's dance leads to": "Darunias Joy",
  "mastery of horseback archery grants": "Horseback Archery 1500 Points",
  "scoring 1500 in horseback archery grants": "Horseback Archery 1500 Points",
  "staring into the sun grants": "Lake Hylia Sun",
  "shooting the sun grants": "Lake Hylia Sun",
  "playing Sun's Song in a grave spawns": "Heart Piece Grave Chest",
  "in Goron City the hammer unlocks": "Goron City Leftmost Maze Chest",
  "a storm near the castle reveals": "GS Hyrule Castle Grotto",
  "buried near the valley a spider holds": "GS Hyrule Field Near Gerudo Valley",
  "a spider high above the icy waters holds": "GS Zora's Fountain Hidden Cave",
  "deep in the forest, shadows guard a chest containing": "Forest Temple Floormaster Chest",
  "a Floormaster in Forest Temple guards": "Forest Temple Floormaster Chest",
  "high in the Fire Temple, Pierre hid": "Fire Temple Scarecrow Chest",
  "high in the Fire Temple, Flare Dancers hid": "Fire Temple MQ West Tower Top Chest/Fire Temple Megaton Hammer Chest",
  "deep under the lake, beyond the currents, hides": "Water Temple River Chest",
  "the Water Temple River Chest holds": "Water Temple River Chest",
  "deep under the lake, the gilded chest contains": "Water Temple MQ Boss Key Chest/Water Temple Boss Key Chest",
  "the Water Temple Gilded Chest holds": "Water Temple MQ Boss Key Chest/Water Temple Boss Key Chest",
  "deep under the lake, the apparent key is really": "Water Temple MQ Freestanding Key",
  "deep under the lake, the locked spider holds": "GS Water Temple MQ North Basement",
  "those who seek sunken silver rupees will find": "Gerudo Training Grounds MQ Underwater Silver Rupee Chest/Gerudo Training Grounds Underwater Silver Rupee Chest",
  "the final prize of the thieves' training is": "Gerudo Training Grounds MQ Ice Arrows Chest/Gerudo Training Grounds Maze Path Final Chest",
  "Dead Hand holds": "Bottom of the Well MQ Compass Chest/Bottom of the Well Defeat Boss",
  "Dead Hand in the well holds": "Bottom of the Well MQ Compass Chest/Bottom of the Well Defeat Boss",
  "upon the Colossus's right hand is": "Silver Gauntlets Chest",
  "upon the Colossus's left hand is": "Mirror Shield Chest",
  "within the Colossus a temporal paradox yields": "Spirit Temple MQ Child Center Chest",
  "within the Colossus a symphony yields": "Spirit Temple MQ Lower Adult Right Chest",
  "within the Colossus a spider's symphony yields": "GS Spirit Temple MQ Lower Adult Right",
  "shadows in an invisible maze guard": "Shadow Temple MQ Bomb Flower Chest/Shadow Temple Hidden Floormaster Chest",
  "after a free boat ride comes": "Shadow Temple MQ Bomb Flower Chest/Shadow Temple Hidden Floormaster Chest",
  "deep in the Wasteland is": "Haunted Wasteland Structure Chest",
  "beneath the sands, flames reveal": "Haunted Wasteland Structure Chest",
  "in the Composers' Grave, darkness hides": "Composer Grave Chest",
  "the Composer Brothers hid": "Composer Grave Chest",
  "in the Composers' Grave, ReDead guard": "Song from Composer Grave",
  "the Composer Brothers wrote": "Song from Composer Grave",
  "deep in the forest Sheik teaches": "Sheik Forest Song",
  "Sheik waits at a monument to time to teach": "Sheik at Temple",
  "the crater's melody is": "Sheik in Crater",
  "the frozen cavern echoes with": "Sheik in Ice Cavern",
  "a ravaged village mourns with": "Sheik in Kakariko",
  "a hero ventures beyond the Wasteland to learn": "Sheik at Colossus",
  "under the icy waters lies": "Zoras Fountain Bottom Freestanding PoH",
  "riding a beanstalk in the desert leads to": "Colossus Freestanding PoH",
  "riding a beanstalk in the crater leads to": "DM Crater Volcano Freestanding PoH",
  "spinning Goron pottery contains": "Goron City Pot Freestanding PoH",
  "within a tree, a temporal stone contains": "Deku Tree MQ After Spinning Log Chest",
  "in the belly of a deity, a spider surrounded by shadows holds": "GS Jabu Jabu MQ Invisible Enemies Room",
  'an ancient tree': 'Deku Tree',
  'Deku Tree': 'Deku Tree',
  'an immense cavern': 'Dodongos Cavern',
  'Dodongo\'s Cavern': 'Dodongos Cavern',
  'the belly of a deity': 'Jabu Jabus Belly',
  'Jabu Jabu\'s Belly': 'Jabu Jabus Belly',
  'a deep forest': 'Forest Temple',
  'Forest Temple': 'Forest Temple',
  'a high mountain': 'Fire Temple',
  'Fire Temple': 'Fire Temple',
  'a vast lake': 'Water Temple',
  'Water Temple': 'Water Temple',
  'the house of the dead': 'Shadow Temple',
  'Shadow Temple': 'Shadow Temple',
  'the goddess of the sand': 'Spirit Temple',
  'Spirit Temple': 'Spirit Temple',
  'a frozen maze': 'Ice Cavern',
  'Ice Cavern': 'Ice Cavern',
  'a shadow\'s prison': 'Bottom of the Well',
  'Bottom of the Well': 'Bottom of the Well',
  'the test of thieves': 'Gerudo Training Grounds',
  'Gerudo Training Grounds': 'Gerudo Training Grounds',
  'outside Ganon\'s Castle': 'Outside Ganon\'s Castle',
  'a conquered citadel': 'Ganon\'s Castle',
  'Ganon\'s Castle': 'Ganon\'s Castle',
  'Death Mountain Trail': 'Death Mountain Trail',
  'Graveyard': 'Graveyard',
  'Goron City': 'Goron City',
  'Lost Woods': 'Lost Woods',
  'Temple of Time': 'Temple of Time',
  'Haunted Wasteland': 'Haunted Wasteland',
  'Desert Colossus': 'Desert Colossus',
  'Lost Woods': 'Lost Woods',
  'Kokiri Forest': 'Kokiri Forest',
  'Death Mountain Crater': 'Death Mountain Crater',
  'Desert Colossus': 'Desert Colossus',
  'Lon Lon Ranch': 'Lon Lon Ranch',
  'Sacred Forest Meadow': 'Sacred Forest Meadow',
  'Gerudo\'s Fortress': 'Gerudo Fortress',
  'Kakariko Village': 'Kakariko Village',
  'Market': 'Market',
  'Gerudo Valley': 'Gerudo Valley',
  'Lake Hylia': 'Lake Hylia',
  'Zora\'s River': 'Zora\'s River',
  'Zora\'s Domain': 'Zora\'s Domain',
  'Zora\'s Fountain': 'Zora\'s Fountain',
  'Hyrule Castle': 'Hyrule Castle',
  'Hyrule Field': 'Hyrule Field',
};

var warpSongs = ['Minuet of Forest', 'Bolero of Fire', 'Serenade of Water', 'Nocturne of Shadow', 'Requiem of Spirit', 'Prelude of Light'];

var songTargets = {
  'Minuet of Forest': 'Sacred Forest Meadow',
  'Bolero of Fire': 'Death Mountain Crater',
  'Serenade of Water': 'Lake Hylia',
  'Nocturne of Shadow': 'Above Graveyard',
  'Requiem of Spirit': 'Desert Colossus',
  'Prelude of Light': 'Temple of Time'
}

var bosses = {
  'Links Pocket': 'Free',
  'Queen Gohma': 'Deku Tree',
  'King Dodongo': 'Dodongos Cavern',
  'Barinade': 'Jabu Jabus Belly',
  'Phantom Ganon': 'Forest Temple',
  'Volvagia': 'Fire Temple',
  'Morpha': 'Water Temple',
  'Bongo Bongo': 'Shadow Temple',
  'Twinrova': 'Spirit Temple'
};

var regionChangingChecks = {
  'Impa at Castle': 'Hyrule Field',
  'Queen Gohma': 'Kokiri Forest',
  'King Dodongo': 'Death Mountain Trail',
  'Barinade': 'Zoras Fountain',
  'Phantom Ganon': 'Kokiri Forest',
  'Volvagia': 'Death Mountain Crater',
  'Morpha': 'Lake Hylia',
  'Bongo Bongo': 'Above Graveyard',
  'Twinrova': 'Desert Colossus',
};

var locationsByRegionChild = {
  'LW Bridge From Forest': [''],
  'Kokiri Forest': [
      'KF Midos Top Left Chest', 'KF Midos Top Right Chest', 'KF Midos Bottom Left Chest', 'KF Midos Bottom Right Chest',
      'KF Kokiri Sword Chest', 'KF Storms Grotto Chest'
  ],
  'Deku Tree': ['Deku Tree Map Chest', 'Deku Tree Compass Chest',
      'Deku Tree Compass Room Side Chest', 'Deku Tree Basement Chest', 'Deku Tree Slingshot Chest',
      'Deku Tree Slingshot Room Side Chest',
      'Deku Tree Queen Gohma Heart', 'Queen Gohma'
  ],
  'Lost Woods': [
      'LW Gift from Saria',
      'LW Ocarina Memory Game',
      'LW Target in Woods',
      'LW Near Shortcuts Grotto Chest',
      'Deku Theater Skull Mask',
      'LW Skull Kid',
      'LW Deku Scrub Near Bridge',
      'LW Deku Scrub Grotto Front'
  ],
  'Sacred Forest Meadow': [
      'Song from Saria', 'SFM Wolfos Grotto Chest'
  ],
  'Hyrule Field': [
      'HF Ocarina of Time Item',
      'HF Near Market Grotto Chest',
      'HF Tektite Grotto Freestanding PoH',
      'HF Southeast Grotto Chest',
      'HF Open Grotto Chest', 
      "HF Deku Scrub Grotto"
  ],
  'Market': [
      'Market Shooting Gallery Reward',
      'Market Bombchu Bowling First Prize',
      'Market Bombchu Bowling Second Prize',
      'Market Bombchu Bowling Bombchus',
      'Market Lost Dog',
      'Market Treasure Chest Game Reward'
  ],
  'Temple of Time': ['Check Pedestal (Stones)'],
  'Hyrule Castle': ['HC Great Fairy Reward'],
  'Lon Lon Ranch': [
      'Song from Malon',
      'LLR Talons Chickens',
      'LLR Freestanding PoH'
  ],
  'Lake Hylia': [
      'LH Underwater Item',
      'LH Child Fishing',
      'LH Lab Dive'
  ],
  'Gerudo Valley': [
      'GV Crate Freestanding PoH',
      'GV Waterfall Freestanding PoH'
  ],
  'Desert Colossus': [
      'Colossus Great Fairy Reward',
      'Colossus Freestanding PoH',
      'Sheik at Colossus'
  ],
  'Haunted Wasteland': ['Wasteland Chest'],
  'Spirit Temple': [
      'Spirit Temple Child Bridge Chest',
      'Spirit Temple Child Early Torches Chest',
      'Spirit Temple Child Climb North Chest',
      'Spirit Temple Child Climb East Chest',
      'Spirit Temple Map Chest',
      'Spirit Temple Sun Block Room Chest',
      'Spirit Temple Silver Gauntlets Chest'
  ],
  'Kakariko Village': [
      'Kak Anju as Child',
      'Kak Impas House Freestanding PoH',
      'Kak Man on Roof',
      'Kak Open Grotto Chest',
      'Kak Redead Grotto Chest',
      'Kak 10 Gold Skulltula Reward',
      'Kak 20 Gold Skulltula Reward',
      'Kak 30 Gold Skulltula Reward',
      'Kak 40 Gold Skulltula Reward',
      'Kak 50 Gold Skulltula Reward'
  ],
  'Bottom of the Well': [
      'Bottom of the Well Front Left Fake Wall Chest',
      'Bottom of the Well Front Center Bombable Chest',
      'Bottom of the Well Back Left Bombable Chest',
      'Bottom of the Well Underwater Left Chest',
      'Bottom of the Well Freestanding Key',
      'Bottom of the Well Compass Chest',
      'Bottom of the Well Center Skulltula Chest',
      'Bottom of the Well Right Bottom Fake Wall Chest',
      'Bottom of the Well Fire Keese Chest',
      'Bottom of the Well Like Like Chest',
      'Bottom of the Well Map Chest',
      'Bottom of the Well Underwater Front Chest',
      'Bottom of the Well Invisible Chest',
      'Bottom of the Well Lens of Truth Chest'
  ],
  'Above Graveyard': [],
  'Graveyard': [
      "Song from Composers Grave",
      'Graveyard Shield Grave Chest',
      'Graveyard Heart Piece Grave Chest',
      'Graveyard Composers Grave Chest',
      'Graveyard Freestanding PoH',
      'Graveyard Dampe Gravedigging Tour',
  ],
  'Death Mountain Trail': [
      'DMT Freestanding PoH',
      'DMT Chest',
      'DMT Storms Grotto Chest',
      'DMT Great Fairy Reward'
  ],
  'Death Mountain Crater': [
      'DMC Wall Freestanding PoH',
      'DMC Upper Grotto Chest',
      'DMC Great Fairy Reward'
  ],
  'Goron City': [
      'GC Darunias Joy',
      'GC Pot Freestanding PoH',
      'GC Rolling Goron as Child',
      'GC Maze Right Chest',
      'GC Maze Center Chest'
  ],
  'Dodongos Cavern': [
      'Dodongos Cavern Map Chest',
      'Dodongos Cavern Compass Chest',
      'Dodongos Cavern Bomb Flower Platform Chest',
      'Dodongos Cavern Bomb Bag Chest',
      'Dodongos Cavern End of Bridge Chest',
      'Dodongos Cavern Boss Room Chest',
      'Dodongos Cavern King Dodongo Heart', 'King Dodongo'
  ],
  'Zora River': [
      'ZR Magic Bean Salesman',
      "ZR Frogs in the Rain",
      "ZR Frogs Ocarina Game",
      'ZR Open Grotto Chest',
      'ZR Near Open Grotto Freestanding PoH',
      'ZR Near Domain Freestanding PoH'
  ],
  'Zoras Domain': ['ZD Diving Minigame', 'ZD Chest'],
  'Zoras Fountain': ['ZF Great Fairy Reward'],
  'Jabu Jabus Belly': ['Jabu Jabus Belly Boomerang Chest',
      'Jabu Jabus Belly Map Chest',
      'Jabu Jabus Belly Compass Chest',
      'Jabu Jabus Belly Barinade Heart',
                       , 'Barinade'
  ]
};

var skulltulasByRegionChild = {
  'Kokiri Forest': ['GS Kokiri Know It All House', 'GS Kokiri Bean Patch'],
  'Deku Tree': ['GS Deku Tree Compass Room', 'GS Deku Tree Basement Vines', 'GS Deku Tree Basement Gate', 'GS Deku Tree Basement Back Room'],
  'Lost Woods': ['GS Lost Woods Bean Patch Near Bridge', 'GS Lost Woods Bean Patch Near Stage'],
  'Sacred Forest Meadow': [],
  'Hyrule Field': ['GS Hyrule Field near Kakariko', 'GS Hyrule Field Near Gerudo Valley'],
  'Market': ['GS Castle Market Guard House'],
  'Temple of Time': [],
  'Hyrule Castle': ['GS Hyrule Castle Tree', 'GS Hyrule Castle Grotto'],
  'Lon Lon Ranch': ['GS Lon Lon Ranch Tree', 'GS Lon Lon Ranch Rain Shed', 'GS Lon Lon Ranch House Window', 'GS Lon Lon Ranch Back Wall'],
  'Lake Hylia': ['GS Lake Hylia Bean Patch', 'GS Lake Hylia Lab Wall', 'GS Lake Hylia Small Island'],
  'Gerudo Valley': ['GS Gerudo Valley Small Bridge', 'GS Gerudo Valley Bean Patch'],
  'Desert Colossus': ['GS Desert Colossus Bean Patch'],
  'Haunted Wasteland': ['GS Wasteland Ruins'],
  'Spirit Temple': ['GS Spirit Temple Metal Fence', 'GS Spirit Temple Bomb for Light Room', 'GS Spirit Temple Hall to West Iron Knuckle'],
  'Kakariko Village': ['GS Kakariko House Under Construction', 'GS Kakariko Skulltula House', 'GS Kakariko Guard\'s House', 'GS Kakariko Tree', 'GS Kakariko Watchtower'],
  'Bottom of the Well': ['GS Well West Inner Room', 'GS Well East Inner Room', 'GS Well Like Like Cage'],
  'Above Graveyard': [],
  'Graveyard': ['GS Graveyard Wall', 'GS Graveyard Bean Patch'],
  'Death Mountain Trail': ['GS Mountain Trail Bean Patch', 'GS Mountain Trail Bomb Alcove'],
  'Death Mountain Crater': ['GS Death Mountain Crater Crate', 'GS Mountain Crater Bean Patch'],
  'Goron City': ['GS Goron City Boulder Maze'],
  'Dodongos Cavern': ['GS Dodongo\'s Cavern East Side Room', 'GS Dodongo\'s Cavern Vines Above Stairs', 'GS Dodongo\'s Cavern Back Room', 'GS Dodongo\'s Cavern Alcove Above Stairs'],
  'Zora River': ['GS Zora River Ladder', 'GS Zora River Tree'],
  'Zoras Domain': [],
  'Zoras Fountain': ['GS Zora\'s Fountain Tree', 'GS Zora\'s Fountain Above the Log'],
  'Jabu Jabus Belly': ['GS Jabu Jabu Water Switch Room', 'GS Jabu Jabu Lobby Basement Lower', 'GS Jabu Jabu Lobby Basement Upper', 'GS Jabu Jabu Near Boss'],
}

var utilityByRegionChild = {
  'Kakariko Village': ['Turn in Keaton Mask'],
  'Market': ['Buy Keaton Mask', 'Buy Skull Mask'],
  'Spirit Temple': ['Unlock First Door'],
}
var entrancesByRegionChild = {
  'LW Bridge From Forest': ['Kokiri Forest', 'Hyrule Field'],
  'Kokiri Forest': ['Deku Tree', 'Lost Woods', 'Hyrule Field'],
  'Deku Tree': ['Kokiri Forest'],
  'Lost Woods': ['Kokiri Forest', 'Goron City', 'Zora River', 'Sacred Forest Meadow'],
  'Sacred Forest Meadow': ['Lost Woods'],
  'Hyrule Field': ['Kokiri Forest', 'Market', 'Kakariko Village', 'Zora River', 'Lon Lon Ranch', 'Gerudo Valley', 'Lake Hylia'],
  'Market': ['Hyrule Field', 'Temple of Time', 'Hyrule Castle'],
  'Temple of Time': ['Market', 'Pull Master Sword'],
  'Hyrule Castle': ['Market'],
  'Lon Lon Ranch': ['Hyrule Field'],
  'Lake Hylia': ['Hyrule Field', 'Zoras Domain'],
  'Gerudo Valley': ['Hyrule Field', 'Lake Hylia'],
  'Desert Colossus': ['Spirit Temple', 'Haunted Wasteland'],
  'Haunted Wasteland': ['Desert Colossus'],
  'Spirit Temple': ['Desert Colossus'],
  'Kakariko Village': ['Hyrule Field', 'Bottom of the Well', 'Death Mountain Trail', 'Graveyard'],
  'Bottom of the Well': ['Kakariko Village'],
  'Above Graveyard': ['Graveyard'],
  'Graveyard': ['Kakariko Village'],
  'Death Mountain Trail': ['Death Mountain Crater', 'Goron City', 'Kakariko Village', 'Dodongos Cavern'],
  'Death Mountain Crater': ['Death Mountain Trail'],
  'Goron City': ['Lost Woods', 'Death Mountain Trail'],
  'Dodongos Cavern': ['Death Mountain Trail'],
  'Zora River': ['Zoras Domain', 'Lost Woods', 'Hyrule Field'],
  'Zoras Domain': ['Zoras Fountain', 'Zora River', 'Lake Hylia'],
  'Zoras Fountain': ['Zoras Domain', 'Jabu Jabus Belly'],
  'Jabu Jabus Belly': ['Zoras Fountain'],
};

var gossipStonesByRegionChild = {
    'Death Mountain Crater': ['Bombable Wall'],
    'Death Mountain Trail': ['Biggoron'],
    'Desert Colossus': ['Spirit Temple'],
    'Dodongos Cavern': ['Bombable Wall'],
    'Gerudo Valley': ['Waterfall'],
    'Goron City': ['Maze', 'Medigoron'],
    'Above Graveyard': ['Shadow Temple'],
    'Hyrule Castle': ['Malon', 'Rock Wall'],
    'Kokiri Forest': ['Deku Tree Left', 'Deku Tree Right'],
    'Lake Hylia': ['Lab', 'Southeast Corner', 'Southwest Corner'],
    'Lost Woods': ['Bridge'],
    'Sacred Forest Meadow': ['Maze Lower', 'Maze Upper', 'Saria'],
    'Temple of Time': ['Left', 'Left-Center', 'Right', 'Right-Center'],
    'Zoras Domain': ['Mweep'],
    'Zoras Fountain': ['Fairy', 'Jabu'],
    'Zoras River': ['Plateau', 'Waterfall'],
};

var locationsByRegionAdult = {
  "Kokiri Forest": ["KF Midos Top Left Chest", "KF Midos Top Right Chest", "KF Midos Bottom Left Chest", "KF Midos Bottom Right Chest", "KF Storms Grotto Chest"],
  "Lost Woods": ["LW Near Shortcuts Grotto Chest", "LW Deku Scrub Grotto Front"],
  "Sacred Forest Meadow": ["SFM Wolfos Grotto Chest", "Sheik in Forest"],
  "Forest Temple": ["Forest Temple First Room Chest", "Forest Temple First Stalfos Chest", "Forest Temple Raised Island Courtyard Chest", "Forest Temple Map Chest", "Forest Temple Well Chest", "Forest Temple Eye Switch Chest", "Forest Temple Boss Key Chest", "Forest Temple Floormaster Chest", "Forest Temple Red Poe Chest", "Forest Temple Bow Chest", "Forest Temple Blue Poe Chest", "Forest Temple Falling Ceiling Room Chest", "Forest Temple Basement Chest", "Forest Temple Phantom Ganon Heart", "Phantom Ganon"],
  "Hyrule Field": ["HF Near Market Grotto Chest", "HF Tektite Grotto Freestanding PoH", "HF Southeast Grotto Chest", "HF Open Grotto Chest", "HF Deku Scrub Grotto"],
  "Market": ["Market 10 Big Poes"],
  "Temple of Time": ["Sheik at Temple", "Zelda", "Check Pedestal (Medallions)"],
  "Lon Lon Ranch": [],
  "Lake Hylia": ["LH Adult Fishing", "LH Lab Dive", "LH Freestanding PoH", "LH Sun"],
  "Water Temple": ["Water Temple Longshot Chest", "Water Temple Compass Chest", "Water Temple Map Chest", "Water Temple Cracked Wall Chest", "Water Temple Torches Chest", "Water Temple Boss Key Chest", "Water Temple Central Pillar Chest", "Water Temple Central Bow Target Chest", "Water Temple River Chest", "Water Temple Dragon Chest", "Water Temple Morpha Heart", "Morpha"],
  "Gerudo Valley": ["GV Crate Freestanding PoH", "GV Waterfall Freestanding PoH", "GV Chest"],
  "Gerudo Fortress": ["GF Chest", "GF HBA 1000 Points", "GF HBA 1500 Points"],
  "Gerudo Training Grounds": ["Gerudo Training Grounds Underwater Silver Rupee Chest", "Gerudo Training Grounds Lobby Left Chest", "Gerudo Training Grounds Lobby Right Chest", "Gerudo Training Grounds Stalfos Chest", "Gerudo Training Grounds Before Heavy Block Chest", "Gerudo Training Grounds Heavy Block First Chest", "Gerudo Training Grounds Heavy Block Second Chest", "Gerudo Training Grounds Heavy Block Third Chest", "Gerudo Training Grounds Heavy Block Fourth Chest", "Gerudo Training Grounds Eye Statue Chest", "Gerudo Training Grounds Near Scarecrow Chest", "Gerudo Training Grounds Hammer Room Clear Chest", "Gerudo Training Grounds Hammer Room Switch Chest", "Gerudo Training Grounds Freestanding Key", "Gerudo Training Grounds Maze Right Central Chest", "Gerudo Training Grounds Maze Right Side Chest", 'Gerudo Training Grounds Underwater Silver Rupee Chest"', "Gerudo Training Grounds Beamos Chest", "Gerudo Training Grounds Hidden Ceiling Chest", "Gerudo Training Grounds Maze Path First Chest", "Gerudo Training Grounds Maze Path Second Chest", "Gerudo Training Grounds Maze Path Third Chest", "Gerudo Training Grounds Maze Path Final Chest"],
  "Haunted Wasteland": ["Wasteland Chest"],
  "Desert Colossus": ["Colossus Freestanding PoH", "Colossus Fairy Reward", "Sheik at Colossus"],
  "Spirit Temple": ["Spirit Temple Child Climb North Chest", "Spirit Temple Child Climb East Chest", "Spirit Temple Map Chest", "Spirit Temple Sun Block Room Chest", "Spirit Temple Silver Gauntlets Chest", "Spirit Temple Compass Chest", "Spirit Temple Early Adult Right Chest", "Spirit Temple First Mirror Left Chest", "Spirit Temple First Mirror Right Chest", "Spirit Temple Statue Room Northeast Chest", "Spirit Temple Statue Room Hand Chest", "Spirit Temple Near Four Armos Chest", "Spirit Temple Hallway Right Invisible Chest", "Spirit Temple Hallway Left Invisible Chest", "Spirit Temple Mirror Shield Chest", "Spirit Temple Boss Key Chest", "Spirit Temple Topmost Chest", "Spirit Temple Twinrova Heart", "Twinrova"],
  "Kakariko Village": ["Song from Windmill", "Kak Anju as Adult", "Kak Impas House Freestanding PoH", "Kak Windmill Freestanding PoH", "Kak Man on Roof", "Kak Open Grotto Chest", "Kak Redead Grotto Chest", "Kak Shooting Gallery Reward", "Kak 10 Gold Skulltula Reward", "Kak 20 Gold Skulltula Reward", "Kak 30 Gold Skulltula Reward", "Kak 40 Gold Skulltula Reward", "Kak 50 Gold Skulltula Reward"],
  "Graveyard": ["Song from Composers Grave", "Graveyard Shield Grave Chest", "Graveyard Heart Piece Grave Chest", "Graveyard Composers Grave Chest", "Graveyard Freestanding PoH", "Graveyard Hookshot Chest", "Graveyard Dampe Race Freestanding PoH"],
  "Shadow Temple": ["Shadow Temple vanilla", "Shadow Temple Map Chest", "Shadow Temple Hover Boots Chest", "Shadow Temple Compass Chest", "Shadow Temple Early Silver Rupee Chest", "Shadow Temple Invisible Blades Visible Chest", "Shadow Temple Invisible Blades Invisible Chest", "Shadow Temple Falling Spikes Lower Chest", "Shadow Temple Falling Spikes Upper Chest", "Shadow Temple Falling Spikes Switch Chest", "Shadow Temple Invisible Spikes Chest", "Shadow Temple Freestanding Key", "Shadow Temple Wind Hint Chest", "Shadow Temple After Wind Enemy Chest", "Shadow Temple After Wind Hidden Chest", "Shadow Temple Spike Walls Left Chest", "Shadow Temple Boss Key Chest", "Shadow Temple Invisible Floormaster Chest", "Shadow Temple Bongo Bongo Heart", "Bongo Bongo"],
  "Death Mountain Trail": ["DMT Freestanding PoH", "DMT Chest", "DMT Storms Grotto Chest", "DMT Great Fairy Reward", "DMT Biggoron"],
  "Death Mountain Crater": ["DMC Volcano Freestanding PoH", "DMC Wall Freestanding PoH", "DMC Upper Grotto Chest", "DMC Great Fairy Reward", "Sheik in Crater"],
  "Fire Temple": ["Fire Temple Near Boss Chest", "Fire Temple Flare Dancer Chest", "Fire Temple Boss Key Chest", "Fire Temple Big Lava Room Lower Open Door Chest", "Fire Temple Big Lava Room Blocked Door Chest", "Fire Temple Boulder Maze Lower Chest", "Fire Temple Boulder Maze Side Room Chest", "Fire Temple Map Chest", "Fire Temple Boulder Maze Shortcut Chest", "Fire Temple Boulder Maze Upper Chest", "Fire Temple Scarecrow Chest", "Fire Temple Compass Chest", "Fire Temple Megaton Hammer Chest", "Fire Temple Highest Goron Chest", "Fire Temple Volvagia Heart", "Volvagia"],
  "Goron City": ["GC Rolling Goron as Adult", "GC Maze Left Chest", "GC Maze Right Chest", "GC Maze Center Chest"],
  "Dodongos Cavern": ["Dodongos Cavern Map Chest", "Dodongos Cavern Compass Chest", "Dodongos Cavern Bomb Flower Platform Chest", "Dodongos Cavern Bomb Bag Chest", "Dodongos Cavern End of Bridge Chest", "Dodongos Cavern Boss Room Chest", "Dodongos Cavern King Dodongo Heart", "King Dodongo"],
  "Zora River": ["ZR Open Grotto Chest", "ZR Near Open Grotto Freestanding PoH", "ZR Near Domain Freestanding PoH"],
  "Zoras Domain": ["ZD King Zora Thawed"],
  "Zoras Fountain": ["ZF Iceberg Freestanding PoH", "ZF Bottom Freestanding PoH", "ZF Great Fairy Reward"],
  "Ice Cavern": ["Ice Cavern Map Chest", "Ice Cavern Compass Chest", "Ice Cavern Freestanding PoH", "Ice Cavern Iron Boots Chest", "Sheik in Ice Cavern"],
  "Outside Ganons Castle": ["OGC Great Fairy Reward"],
  "Ganons Castle": ["Ganons Castle Forest Trial Chest", "Ganons Castle Water Trial Left Chest", "Ganons Castle Water Trial Right Chest", "Ganons Castle Shadow Trial Front Chest", "Ganons Castle Shadow Trial Golden Gauntlets Chest", "Ganons Castle Light Trial First Left Chest", "Ganons Castle Light Trial Second Left Chest", "Ganons Castle Light Trial Third Left Chest", "Ganons Castle Light Trial First Right Chest", "Ganons Castle Light Trial Second Right Chest", "Ganons Castle Light Trial Third Right Chest", "Ganons Castle Light Trial Invisible Enemies Chest", "Ganons Castle Light Trial Lullaby Chest", "Ganons Castle Spirit Trial Crystal Switch Chest", "Ganons Castle Spirit Trial Invisible Chest", "Ganons Tower Boss Key Chest"]
};

var skulltulasByRegionAdult = {
  'Kokiri Forest': ['GS Kokiri House of Twins'],
  'Lost Woods': ['GS Lost Woods Above Stage', 'GS Sacred Forest Meadow'],
  'Sacred Forest Meadow': ['GS Sacred Forest Meadow'],
  'Forest Temple': ['GS Forest Temple First Room', 'GS Forest Temple Lobby', 'GS Forest Temple Outdoor East', 'GS Forest Temple Outdoor West', 'GS Forest Temple Basement'],
  'Hyrule Field': ['GS Hyrule Field near Kakariko', 'GS Hyrule Field Near Gerudo Valley'],
  'Market': [],
  'Temple of Time': [],
  'Lon Lon Ranch': [],
  'Lake Hylia': ['GS Lake Hylia Giant Tree', 'GS Lab Underwater Crate'],
  'Water Temple': ['GS Water Temple South Basement', 'GS Water Temple Serpent River', 'GS Water Temple Falling Platform Room', 'GS Water Temple Central Room', 'GS Water Temple Near Boss Key Chest'],
  'Gerudo Valley': ['GS Gerudo Valley Behind Tent', 'GS Gerudo Valley Pillar'],
  'Gerudo Fortress': ['GS Gerudo Fortress Archery Range', 'GS Gerudo Fortress Top Floor'],
  'Gerudo Training Grounds': [],
  'Haunted Wasteland': ['GS Wasteland Ruins'],
  'Desert Colossus': ['GS Desert Colossus Tree', 'GS Desert Colossus Hill'],
  'Spirit Temple': ['GS Spirit Temple Bomb for Light Room', 'GS Spirit Temple Hall to West Iron Knuckle', 'GS Spirit Temple Boulder Room', 'GS Spirit Temple Lobby'],
  'Kakariko Village': ['GS Kakariko Above Impa\'s House'],
  'Graveyard': [],
  'Above Graveyard': [],
  'Shadow Temple': ['GS Shadow Temple Like Like Room', 'GS Shadow Temple Crusher Room', 'GS Shadow Temple Single Giant Pot', 'GS Shadow Temple Near Ship', 'GS Shadow Temple Triple Giant Pot'],
  'Death Mountain Trail': ['GS Mountain Trail Bomb Alcove', 'GS Mountain Trail Path to Crater', 'GS Mountain Trail Above Dodongo\'s Cavern'],
  'Death Mountain Crater': [],
  'Fire Temple': ['GS Fire Temple Song of Time Room', 'GS Fire Temple Unmarked Bomb Wall', 'GS Fire Temple East Tower Climb', 'GS Fire Temple East Tower Top', 'GS Fire Temple Basement'],
  'Goron City': ['GS Goron City Center Platform'],
  'Dodongos Cavern': ['GS Dodongo\'s Cavern East Side Room', 'GS Dodongo\'s Cavern Vines Above Stairs', 'GS Dodongo\'s Cavern Back Room', 'GS Dodongo\'s Cavern Alcove Above Stairs', 'GS Dodongo\'s Cavern Scarecrow'],
  'Zora River': ['GS Zora River Near Raised Grottos', 'GS Zora River Above Bridge'],
  'Zoras Domain': ['GS Zora\'s Domain Frozen Waterfall'],
  'Zoras Fountain': ['GS Zora\'s Fountain Hidden Cave'],
  'Ice Cavern': ['GS Ice Cavern Spinning Scythe Room', 'GS Ice Cavern Heart Piece Room', 'GS Ice Cavern Push Block Room'],
  'Outside Ganons Castle': ['GS Outside Ganon\'s Castle'],
  'Ganons Castle': []
};

var entrancesByRegionAdult = {
  'Kokiri Forest': ['Lost Woods', 'Hyrule Field'],
  'Lost Woods': ['Kokiri Forest', 'Sacred Forest Meadow', 'Goron City', 'Zora River'],
  'Sacred Forest Meadow': ['Forest Temple', 'Lost Woods'],
  'Forest Temple': ['Sacred Forest Meadow'],
  'Hyrule Field': ['Kokiri Forest', 'Market', 'Kakariko Village', 'Zora River', 'Lon Lon Ranch', 'Gerudo Valley', 'Lake Hylia'],
  'Market': ['Hyrule Field', 'Temple of Time', 'Outside Ganons Castle'],
  'Temple of Time': ['Market', 'Place Master Sword'],
  'Lon Lon Ranch': ['Hyrule Field'],
  'Lake Hylia': ['Hyrule Field', 'Water Temple'],
  'Water Temple': ['Lake Hylia'],
  'Gerudo Valley': ['Hyrule Field', 'Lake Hylia', 'Gerudo Fortress'],
  'Gerudo Fortress': ['Haunted Wasteland', 'Gerudo Valley', 'Gerudo Training Grounds'],
  'Gerudo Training Grounds': ['Gerudo Fortress'],
  'Haunted Wasteland': ['Gerudo Fortress', 'Desert Colossus'],
  'Desert Colossus': ['Spirit Temple', 'Haunted Wasteland'],
  'Spirit Temple': ['Desert Colossus'],
  'Kakariko Village': ['Hyrule Field', 'Death Mountain Trail', 'Graveyard'],
  'Graveyard': ['Kakariko Village'],
  'Above Graveyard': ['Shadow Temple', 'Graveyard'],
  'Shadow Temple': ['Above Graveyard'],
  'Death Mountain Trail': ['Death Mountain Crater', 'Goron City', 'Kakariko Village', 'Dodongos Cavern'],
  'Death Mountain Crater': ['Death Mountain Trail', 'Fire Temple', 'Goron City'],
  'Fire Temple': ['Death Mountain Crater'],
  'Goron City': ['Lost Woods', 'Death Mountain Trail', 'Death Mountain Crater'],
  'Dodongos Cavern': ['Death Mountain Trail'],
  'Zora River': ['Zoras Domain', 'Lost Woods', 'Hyrule Field'],
  'Zoras Domain': ['Zoras Fountain', 'Zora River'],
  'Zoras Fountain': ['Zoras Domain', 'Ice Cavern'],
  'Ice Cavern': ['Zoras Fountain'],
  'Outside Ganons Castle': ['Ganons Castle', 'Market'],
  'Ganons Castle': ['Outside Ganons Castle']
};

var utilityByRegionAdult = {};

var gossipStonesByRegionAdult = {
    'Death Mountain Crater': ['Bombable Wall'],
    'Death Mountain Trail': ['Biggoron', 'Storms Grotto'],
    'Desert Colossus': ['Spirit Temple'],
    'Dodongos Cavern': ['Bombable Wall'],
    'Gerudo Valley': ['Waterfall'],
    'Goron City': ['Maze', 'Medigoron'],
    'Above Graveyard': ['Shadow Temple'],
    'Hyrule Castle': ['Malon', 'Rock Wall'],
    'Kokiri Forest': ['Deku Tree Left', 'Deku Tree Right'],
    'Lake Hylia': ['Lab', 'Southeast Corner', 'Southwest Corner'],
    'Lost Woods': ['Bridge'],
    'Sacred Forest Meadow': ['Maze Lower', 'Maze Upper', 'Saria'],
    'Temple of Time': ['Left', 'Left-Center', 'Right', 'Right-Center'],
    'Zoras Domain': ['Mweep'],
    'Zoras Fountain': ['Fairy', 'Jabu'],
    'Zoras River': ['Plateau', 'Waterfall'],
};

// Need to add certain spawns to other maps for logical reasons, add a line saying where the spawn is so players can know the checks they can get?.
var spawnsByRegion = {
    "Kokiri Forest":                 ['Kokiri Forest', 'KF Midos House', 'KF Sarias House', 'KF House of Twins', 'KF Know It All House', 'KF Kokiri Shop', 'KF Links House'],
    "LW Bridge From Forest":         ['LW Bridge From Forest', 'LW Bridge'],
    "Lost Woods":                    ['Lost Woods', 'LW Beyond Mido', 'LW Forest Exit', 'Deku Theater'],
    "Goron City":                    ['GC Woods Warp', 'GC Darunias Chamber', 'Goron City', 'GC Shop'],
    "Zora River":                    ['Zora River', 'ZR Behind Waterfall', 'ZR Front'],
    "Sacred Forest Meadow":          ['SFM Entryway', 'SFM Wolfos Grotto', 'SFM Fairy Grotto'],
    "Hyrule Field":                  ['Hyrule Field'],
    "Lake Hylia":                    ['Lake Hylia', 'LH Lab', 'LH Fishing Hole', 'LH Fishing Island'],
    "Gerudo Valley":                 ['Gerudo Valley', 'GV Fortress Side'],
    "Market":                        ['Market', 'Market Entrance', 'Market Mask Shop', 'Market Guard House', 'Market Bombchu Bowling', 'Market Potion Shop', 'Market Treasure Chest Game',
                                     'Market Bombchu Shop', 'Market Man in Green House', 'Market Shooting Gallery', 'Market Bazaar'],
    "Kakariko Village":              ['Kakariko Village', 'Kak Behind Gate', 'Kak Impas Ledge', 'Kak Potion Shop Front', 'Kak Potion Shop Back', 'Kak Carpenter Boss House',
                                     'Kak House of Skulltula', 'Kak Impas House', 'Kak Impas House Back', 'Kak Odd Medicine Building', 'Kak Shooting Gallery', 'Kak Windmill', 
                                     'Kak Bazaar', 'Kak Redead Grotto', 'Kak Backyard'],
    "Lon Lon Ranch":                 ['Lon Lon Ranch', 'LLR Talons House', 'LLR Stables', 'LLR Tower'],
    "Zoras Domain":                  ['Zoras Domain', 'ZD Behind King Zora', 'ZD Shop'],
    "Gerudo Fortress":               ['Gerudo Fortress', 'GF Outside Gate', 'GV Carpenter Tent'],
    "Haunted Wasteland":             ['Wasteland Near Fortress', 'Wasteland Near Colossus'],
    "Desert Colossus":               ['Desert Colossus', 'Colossus Great Fairy Fountain'],
    "Hyrule Castle":                 ['Castle Grounds', 'HC Great Fairy Fountain'],
    "Temple of Time":                ['ToT Entrance', 'Temple of Time'],
    "Graveyard":                     ['Graveyard', 'Graveyard Dampes House', 'Graveyard Royal Familys Tomb', 'Graveyard Dampes Grave', 'Graveyard Shield Grave', 'Graveyard Heart Piece Grave'],
    "Death Mountain Trail":          ['Death Mountain', 'Death Mountain Summit', 'DMT Great Fairy Fountain'],
    "Death Mountain Crater":         ['DMC Lower Local', 'DMC Lower Nearby', 'DMC Upper Local', 'DMC Upper Nearby', 'DMC Great Fairy Fountain'],
    "Zoras Fountain":                ['Zoras Fountain', 'ZF Great Fairy Fountain'],
    "Outside Ganons Castle":         ['OGC Great Fairy Fountain'],
}

function getSpawn(spawnFromLog) {
  var region;
  Object.keys(spawnsByRegion).forEach(function(item) { 
    if(spawnsByRegion[item].includes(spawnFromLog)) {        
      region = item;
    } 
  })
  return region;
}
